name: "💡 Suggest a feature"
description: "Suggest an idea or improvement"
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does the feature solve?
      placeholder: "It bothers me that …"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Desired solution
      placeholder: "It would be good if …"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives (optional)
      placeholder: "I also considered …"
  - type: checkboxes
    id: checks
    attributes:
      label: Checked beforehand
      options:
        - label: There is no open issue for this idea yet.
          required: true
